### ISSUE TITLE
Settings don't work

### ISSUE THREAD

**Issue by doctormo** [dirkjanm/firefox-send-to-xbmc#11]
In Firefox 35.0.1 (Ubuntu 64bit) the settings page does nothing when the green Add button is pressed. I looked around and the file preferences.js isn't used on the page, which is very odd. The other javascripts (tooltip.js and show passwords work) and there are no console errors reported.

**Comment by dirkjanm** [comment]
Which version of the plugin do you have installed? The latest version should not have this problem.

**Comment by doctormo** [comment]
Version 2.2.0

**Comment by dirkjanm** [comment]
Can you try the plugin in an empty firefox profile and see if the problem occurs there as well?

**Comment by danielandross** [comment]
I have the very same issue on Ubuntu 32bit

**Comment by dirkjanm** [comment]
This is the same as #8 and should be solved already
