### ISSUE TITLE
Username is not stored

### ISSUE THREAD

**Issue by CaNsA** [dirkjanm/firefox-send-to-xbmc#13]
Version 2.2.0
http://i.imgur.com/tde0Ri5.png
Firefox, Window 8.1

**Comment by dirkjanm** [comment]
Do you have storing of passwords disabled by any chance? Username/password combinations are stored in the Firefox password storage, so it may be that if you disabled saving passwords in the settings that this wont work.

**Comment by CaNsA** [comment]
Hi,
    
    The storing of passwords is enabled within firefox on both my
    machines and both wont store the username within the addon.
    
    Cheers
    
    On 16-Mar-2015 09:14, Dirk-jan wrote:
    
    
      Do you have storing of passwords disabled by any chance?
        Username/password combinations are stored in the Firefox
        password storage, so it may be that if you disabled saving
        passwords in the settings that this wont work.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dirkjanm** [comment]
If you have time could you try it in an empty Firefox profile?

**Comment by dirkjanm** [comment]
I'm closing this one due to lack of feedback. Other issues with server settings not remembered were solved in the last version.
