### ISSUE TITLE
plugin configuration disapears on unclean shutdown

### ISSUE THREAD

**Issue by rechapit** [dirkjanm/firefox-send-to-xbmc#16]
Every 1-3 restarts the plugin configuration is lost and all configured servers are missing.

I'm using iceweasel 37 on debian testing

**Comment by rechapit** [comment]
Finally figured out the pattern: when the browser goes through an unclean shutdown like when the browser crashes or is still running when the user logs out then the configuration is lost

**Comment by dirkjanm** [comment]
Do you have this problem with other firefox plugins too? The plugin doesn't use any special methods for saving the configuration, it is a firefox related problem, but I'll look if there is a way to add backup storage methods.

**Comment by rechapit** [comment]
So far this is the only plugin that shows this kind of behavior.
It's almost like the plugin deletes or corrupts the stored configuration when loaded into memory only to write it back on clean exit.

**Comment by dirkjanm** [comment]
I'm not exactly sure how Firefox handles the simple-storage API, but the data is stored in your Firefox profile in the jetpack/jid0-YCM0p5WlCGjvBJcZhAusQ5h26wM@jetpack/simple-storage/store.json file.
You could see when it gets updated and backup it for when it gets corrupted.

**Comment by dirkjanm** [comment]
Losing the configuration json is most likely an issue from Firefox and is not something that can be fixed from the plugin, so I'm closing this one.
