### ISSUE TITLE
support for https

### ISSUE THREAD

**Issue by napopa** [dirkjanm/firefox-send-to-xbmc#17]
Hi, 
I'm using the send to xbmc extension on firefox 37.0.1 for osx and it doesn't seem to work if you use youtube through https.
The send to xbmc logo would just not appear.
Any way to fix this?

Thanks

**Comment by dirkjanm** [comment]
Odd. Are you sure you aren't viewing a video of a playlist? Because there are some known problems with that. https works fine here though.

**Comment by napopa** [comment]
That actually seems to be the case:
https with video of a playlist doesn't work. it does if i switch to http..
