### ISSUE TITLE
Feature request: Vimeo support

### ISSUE THREAD

**Issue by dirkjanm** [dirkjanm/firefox-send-to-xbmc#18]

**Comment by krypt-n** [comment]
I'd suggest a modular system ([like the chrome version](https://github.com/khloke/play-to-xbmc-chrome)) to quickly add new streaming portals and maybe reusing code.
However I could not get it to work with the rightclickparser i.e. it has to show a contextmenu on all pages, not just on video links.

**Comment by evaryont** [comment]
Seems like the URL should be `plugin://plugin.video.vimeo/play/?video_id=<ID>`.

For instance, the url `https://vimeo.com/71902085` would extract 71902085 as the ID.

**Comment by dirkjanm** [comment]
Added in v3.1.0
