### ISSUE TITLE
Feature request: Option to disable YouTube button

### ISSUE THREAD

**Issue by dirkjanm** [dirkjanm/firefox-send-to-xbmc#19]
From https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc/reviews/694698/

**Comment by theBear** [comment]
Agree! Option via right-click is totally sufficient.

**Comment by dirkjanm** [comment]
YouTube button has been removed in 3.0 in favour of a toolbar button which makes more sense and is portable to other websites.
