### ISSUE TITLE
kodi displays error

### ISSUE THREAD

**Issue by LeavingJupiter** [dirkjanm/firefox-send-to-xbmc#23]
When I click the youtube icon from a pc, I get a 'success' confirmation from 'Send to Youtube.' 

On my android tv box, with only kodi running, a popup then appears with a Genesis icon, that says, "Playback Failed, Couldn't locate video URL." The YouTube app doesnt start up 

Can you offer any suggestion?

**Comment by dirkjanm** [comment]
I think this is an issue with your YouTube plugin on Kodi and not with the FireFox plugin that sends it to Kodi. Make sure you have the YouTube plugin installed and that it is up to date.
