### ISSUE TITLE
Sending via context menu from youtube only sends thumbnail

### ISSUE THREAD

**Issue by vrs01** [dirkjanm/firefox-send-to-xbmc#25]
Hi!

When I send a video via the context menu from youtube, Kodi only displays the thumbnail of the video. Could this be changed?

I use Firefox 40 on Windows and Openelec 5.95.5

Best, vrs01

**Comment by dirkjanm** [comment]
Heh, thats a funny bug. I'll fix it in the next version. For now I recommend clicking on the video title instead of on the thumbnail when you want to send it to Kodi.

**Comment by dirkjanm** [comment]
Closing this since this has already been fixed in 2.3.4
