### ISSUE TITLE
Toolbar button

### ISSUE THREAD

**Issue by lameventanas** [dirkjanm/firefox-send-to-xbmc#26]
Instead of changing the DOM, how about using a toolbar button?

The button would normally be disabled and grayed, except when the user is in a website that can be queued or played in Kodi, it would become enabled and colored.

The default action would be to play on the first server, with a dropdown menu to select: Play, Queue, and for each additional server: <servername>/Play <servername>/Queue

The benefit is that it would make it easier to play something in Kodi, no more right clicking or hunting for a button, plus the HTML layout wouldn't be modified, and it would be easier to add support for other websites besides youtube.

**Comment by dirkjanm** [comment]
Yes this feature is on the long-term todo list but hasn't been implemented yet.

**Comment by Matthias84** [comment]
You might want to consider using [Mozilla Social API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API) that is used for the generic [share button + providers](https://blog.mozilla.org/blog/2015/01/13/firefox-enables-you-to-experience-and-share-more-on-the-web/) already.

**Comment by dirkjanm** [comment]
This has been implemented in #60 
Support for more sites to come.
