### ISSUE TITLE
Cannot send Vevo videos (or recent Youtube videos) 

### ISSUE THREAD

**Issue by Scooby-2** [dirkjanm/firefox-send-to-xbmc#28]
I have been using this addon for some while and I love it. But as of today on Linux Mint 17 Qiana running Firefox 42.0 sending to kodi 15.2, the vast majority of youtube videos fail to play on Kodi. This one plays: https://www.youtube.com/watch?v=372436tJiaM
This one doesn't:
https://www.youtube.com/watch?v=-qaB-sxDZwU
No errors are reported but I do get the "Sending to Kodi" and "Sent to Kodi - success" messages on the PC. All I get on Kodi is the usual "Opening stream" box and, if it is at the main menu, the play controls slide in, a small box flashes up in the lower right corner saying "working" and then the controls slide out again. Nothing else happens and there is nothing in the dmesg log.
All VEVO videos that I have tried fail to send and it seems that only very old standard Youtube videos can be sent.

**Comment by dirkjanm** [comment]
The playing and handling of YouTube videos is not done by the Send to Kodi addon, but by the YouTube Kodi plugin (see https://github.com/bromix/plugin.video.youtube).
I do get the same error as you with the second video, which probably indicates a problem with the YouTube plugin (maybe YouTube made a change to their code). I suggest you open an issue there.

As a rule of thumb: whenever sending an url to Kodi and there is a loading screen, then the url arrived safely at Kodi and the job of the Send to Kodi addon is done. Any errors from there are not related to the addon.
