### ISSUE TITLE
Update YouTube plugin url sending syntax

### ISSUE THREAD

**Issue by dirkjanm** [dirkjanm/firefox-send-to-xbmc#29]
Current method is deprecated:

```
18:16:50 T:2672817184 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=-qaB-sxDZwU"
18:16:50 T:2672817184 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=-qaB-sxDZwU"
```

To look at:
- Will this break backwards compatibility with XBMC?

**Comment by honyczek** [comment]
After updating OpenELEC to version 6.0.0 (Kodi 15.2), video is not played. Kodi tries to connect streaming, then appears bubble Working and then nothing happens. Maybe is it because of a new way of plugin call (the issue #29)?

**Comment by dirkjanm** [comment]
It sounds similar to #28 
You would have to look in your Kodi log to be sure but usually when the link arrives at Kodi the addon doesn't have control over it anymore and any problems are related to the YouTube plugin.

**Comment by honyczek** [comment]
#28 is the same, as I wrote. Thanks for your work!
