### ISSUE TITLE
Requires manual login - forgets username

### ISSUE THREAD

**Issue by ronnihh** [dirkjanm/firefox-send-to-xbmc#30]
Hi

Great addon - thanks a lot. Using newly installed Waterfox 40.1.0 against Kodi 15.2. When I try to send a Youtube-video I get a login-failure. If I manually open a tab, and login to Kodi the extension work as intended. 

* I've configured the addon with IP, port, username and password.
* After pressing ADD the options are correctly displayed with password displayed as [hidden]
* Pressing F5 to refresh displays IP, port correctly. Password remains at [hidden] but username is blank

Any idea what could be wrong? Tried reinstalling Waterfox, but i didn't work.

**Comment by dirkjanm** [comment]
I'm not familiar with waterfox, but usernames and passwords are stored in the standard password storage. Maybe you have the storing of passwords disabled?
The passwords should appear in Options -> Security -> Saved logins under sitename starting with addon:jid0-YCM...

**Comment by ronnihh** [comment]
Great! 

I'm using Keepass for password storage, and use the PassIFox-extension to connect Firefox (or in my case Waterfox) to the local Keepass-database. The trouble is that the PassIFox-entension disables the local password storage in Firefox - as all password are instead retrieved from the database. 

I couldn't get PassIFox to retrieve the password for the SendtoKodi-extension from the database, but luckily someone has made another Keepass-connector-extension called KeeFox. This one allows for local passwords combined with the database. Now I'm able to use both SendtoXBMC and my Keepass-database at the same time.

Thank you very much - you pointed me in the right direction.
