### ISSUE TITLE
Forgets server

### ISSUE THREAD

**Issue by rubdos** [dirkjanm/firefox-send-to-xbmc#31]
Hi,

I have to re-enter my server details about weekly. The plugin seems to forget them.

Is it possible that they dissappear when I'm not on the network of the kodi device?

I'm on Arch Linux: % uname -a
Linux localhost 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

Name           : firefox
Version        : 42.0-2
Architecture   : x86_64

Please inform what other data you need to debug this.

Ruben

**Comment by dirkjanm** [comment]
The configuration is stored in your firefox profile, when firefox is not shut down correctly it can happen that this config file gets corrupted. See also #16. Unfortunately there is not much that the plugin can do about this.
