### ISSUE TITLE
Reverse addon url detection

### ISSUE THREAD

**Issue by Matthias84** [dirkjanm/firefox-send-to-xbmc#33]
Hi,

IMHO it's a lot of work for you to add URL syntax for every custom plugin / video service (youtube, vimeo, myvideo, ...). Instead I recommend to talk to the kodi core team to allow the video addons to accept and parse the URLs of the corresponding video service on their own. So you need just to pass the URLs to the Kodi instance and don't need to implement custom URL parsers, addons detection, ... on your own.

**Comment by dirkjanm** [comment]
I've looked at this but every plugin uses their own syntax and this is not really feasible to change via Kodi.
