### ISSUE TITLE
Support OGV & OGA urls (Ogg vorbis videos)

### ISSUE THREAD

**Issue by evaryont** [dirkjanm/firefox-send-to-xbmc#36]
As an example, https://archive.org/details/CompromiseInFreeSoftware can be downloaded in a variety of formats, all of which Kodi can play. However, the "Send to Kodi" menu option isn't available for every format as the extension doesn't detect the URL as something it can play.

**Comment by dirkjanm** [comment]
Closing this since this has already been fixed in 2.3.4
