### ISSUE TITLE
Can't add server with port 80

### ISSUE THREAD

**Issue by riviti** [dirkjanm/firefox-send-to-xbmc#37]
I can't add a server with the following settings:
Name: asdf
Host: 192.168.0.x
Port: 80 or blank
Username, password: blank

I've also tried directly editing simple-storage/store.json while firefox was not running, that only cause the entry I edited to disappear. Also tried removing the file outright, which did nothing.

This works on another computer, so I'm not really sure what's wrong on this one. Suggestions for what I can try?

**Comment by dirkjanm** [comment]
Unfortunately changes that are only present on one computer or can't be solidly reproduced are most likely quirks in firefox and not problems with the plugin. Try it again on an empty profile and see if it works there, aside from that I don't have much advice on how to get it working.
