### ISSUE TITLE
Changing the position of the button

### ISSUE THREAD

**Issue by TomberWolf** [dirkjanm/firefox-send-to-xbmc#45]
Hey,

do you think you could change the position and size of the send to button?

![28-05-_2016_20-23-27](https://cloud.githubusercontent.com/assets/9993839/15629197/e48535aa-2512-11e6-8f92-85c270ba7dc3.jpg)

**Comment by dirkjanm** [comment]
The button has been moved to the URL bar and from the YouTube page in #60
