### ISSUE TITLE
Extension breaks Multiprocess Firefox

### ISSUE THREAD

**Issue by Cerv4ntez** [dirkjanm/firefox-send-to-xbmc#49]
Hi,

could you update this extension so it no longer breaks Multiprocess Firefox?
![grafik](https://cloud.githubusercontent.com/assets/18594385/24994497/5f5f4856-202b-11e7-909c-8791ce042660.png)
more info here:
https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

**Comment by dirkjanm** [comment]
Thanks for bringing this to my attention, I'll have a look at it soon and see if anything needs to be updated to support this.

**Comment by Cerv4ntez** [comment]
my pleasure, currently all existing send to kodi like extensions share this problem, so your`s might be the first to work properly :-)

all that aside, i've been using your extension for a long time and i really appreciate it, so thanks for that.

 

Gesendet: Donnerstag, 13. April 2017 um 10:35 Uhr
Von: Dirk-jan <notifications@github.com>
An: dirkjanm/firefox-send-to-xbmc <firefox-send-to-xbmc@noreply.github.com>
Cc: Cerv4ntez <WIRED79@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [dirkjanm/firefox-send-to-xbmc] Extension breaks Multiprocess Firefox (#49)


Thanks for bringing this to my attention, I'll have a look at it soon and see if anything needs to be updated to support this.

**Comment by dirkjanm** [comment]
Fixed in 2.3.2
