### ISSUE TITLE
Support new youtube web interface

### ISSUE THREAD

**Issue by paol** [dirkjanm/firefox-send-to-xbmc#52]
YT is trialing the next revision of the website (go to youtube.com/new to opt in) which supposedly will roll out to everyone soon.

The "send to kodi" button is missing in the new interface, no doubt because the HTML structure has changed.

**Comment by prometheanfire** [comment]
ya, looks like this rolled out for me at least (and probably others)

**Comment by bluezed** [comment]
Seems to have rolled out to me as well now and the "Send to Kodi" button doesn't show up any more.

Would really appreciate an update to get it working again 👍

**Comment by nicolasochem** [comment]
Same here.

**Comment by dirkjanm** [comment]
Fixed in 4de75e12f843c43b30813f101c504945bac7766f / 2.3.4 which should hit AMO as soon as it is approved.
