### ISSUE TITLE
switch to webextension?

### ISSUE THREAD

**Issue by alex1702** [dirkjanm/firefox-send-to-xbmc#53]
with firefox 57 only webextension addons works. do you have a plan to change your addon to webextension?

**Comment by gerv** [comment]
@dirkjanm: ping? It would be useful to know if you plan to update this addon to be compatible with Firefox 57. Thanks :-)

**Comment by dirkjanm** [comment]
Planning certainly, just no solid ETA yet. I'll start with looking into how much work is required to change the addon soon.

**Comment by janhicken** [comment]
This change would be greatly appreciated as the addon wouldn't work any more from mid of november on

**Comment by dirkjanm** [comment]
c8697d2708730ca1901e0fffc52aec8dbca6ab47 switches the addon to full WebExtension only.
It is currently available for testing with FireFox 57 at https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc-kodi/versions/beta?page=1#version-3.0.0b1

It is still missing the "Send to Kodi" button on the YouTube page, but the rightclick features should be working. If not, please open an issue so I can have a look.

**Comment by dirkjanm** [comment]
This is now fixed in #60 and will be live on AMO as soon as the plugin is reviewed.
