### ISSUE TITLE
Network Error  Could not Contact Kodi

### ISSUE THREAD

**Issue by aZz7eCh** [dirkjanm/firefox-send-to-xbmc#54]
Hi Guys.  I have been using Send to Kodi for at least a year.  Great little tool for allowing me to send whatever video I'm watching here, to my OpenELEC RPI running my TV on the wall.

However ... about a month ago ... I started experiencing the following messages every time I try to use the addon:
Sending  Sending to Kodi.
Network Error  Could not Contact Kodi.  Check your configuration.

The IP's entered as my server are correct ... everything is used as it always was, but I keep getting the same message every time.

I have uninstalled/removed the Send to Kodi addon in my Firefox many times.  Doesn't help.

KORE on my android phone, can communicate and send stuff just fine to my OPENELEC RPI still ... so problem seems to be limited to my desktop.

If anyone can throw any suggestions my way I'd really appreciate it ...
I am running Debian 8 with Firefox ESR.

**Comment by dirkjanm** [comment]
Did you verify that the port is correct in the settings? The default port changed in the last version, so if your settings somehow do not have a port set, it will pick a wrong default port.
Uninstalling the addon does not remove the settings I think, deleting the server, then saving the settings, then adding the server again could maybe help.

**Comment by aZz7eCh** [comment]
.. always the simplest of reasons.
So KORE on our Tablets/Phones was obviously detecting the new port.

TY!  Appreciated.  Resurrected.
