### ISSUE TITLE
Feature Request: Support for Seamonkey

### ISSUE THREAD

**Issue by barcoboy** [dirkjanm/firefox-send-to-xbmc#56]
It would be great if this plugin also worked in Seamonkey, as right now when you try to install it, Seamonkey says that it is not compatible.

**Comment by dirkjanm** [comment]
I'm not familiar with Seamonkey, so I don't know exactly what the differences are addon wise. I'll have to investigate this but since the majority of users use Firefox, it won't have a very high priority.

**Comment by dirkjanm** [comment]
There is a converter available here: http://addonconverter.fotokraina.com/
It didn't complain when I pointed it to the mozilla addons url, so it might work without changes in seamonkey.
Can you try it and let me know the results?

**Comment by barcoboy** [comment]
Many thanks for sending me the link to the converter.  I gave it a try with the latest version of Seamonkey (2.46), and it works great!  Appreciate the quick reply and taking the time to find a solution for me.

**Comment by dirkjanm** [comment]
Glad to hear it works!
