### ISSUE TITLE
Lost settings

### ISSUE THREAD

**Issue by josch** [dirkjanm/firefox-send-to-xbmc#57]
Hi,

since today (and probably caused by the update to version 2.3.5-fix1) the send to kodi plugin of me and my wife lost its settings. We are running firefox version 45.9.0 and 55.0.2, respectively and neither of us messed around with our profile. But both of us received the October 1 update which lets us believe that it is the culprit for the issues we see.

In my case (firefox 55.0.2) I can just re-enter the server details and I'm good again. But in my wife's case (firefox 45.9.0), clicking the "Add" button to insert a new server literally has no effect at all (nothing happens when clicking it).

It would be great if settings didn't get lost and if there was no regression with firefox 45.9.0.

Thanks!

cheers, josch

**Comment by dirkjanm** [comment]
Hi Josch,

Thanks for letting me know. I will investigate why this is happening. The most likely cause is that in the latest version, there has been some changes in the plugin to modernize it for Firefox 57. However this should not have caused a loss of settings.
As for the case with Firefox 45, I think this is a compatibility issue as that version is quite old and does not support the newer features added. I will investigate this as well and update the compatibility if needed.

**Comment by dirkjanm** [comment]
I'm not sure what caused the loss of settings. However, I've updated the compatibility details for 2.3.5 and excluded unsupported versions. You should be able to install the previous version https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc-kodi/versions/2.3.4 on Firefox 45 and you should be able to use the plugin again.
