### ISSUE TITLE
Server not recognised as configured if username and password not set

### ISSUE THREAD

**Issue by gerv** [dirkjanm/firefox-send-to-xbmc#58]
STR:

* Install "Send to Kodi"
* Set up server. Name: "Slice". IP: "192.168.0.6". Port: "80".
* Right-click a YouTube link

Expected: "Send to Slice" or similar
Actual: "Set up server for Send to Kodi"

It seems like you need to configure a username and password before the addon will recognise that you've configured a server. But IIRC, my Kodi doesn't have one.

**Comment by dirkjanm** [comment]
Can you let me know which version you are using? I'm working on v3.0 now so that one might still have some bugs.

**Comment by gerv** [comment]
I'm using Send to Kodi 3.0.0b1 on Firefox 58.0a1 on Ubuntu Linux 16.04 LTS.

**Comment by dirkjanm** [comment]
Fixed it, though the issue was not related to the missing username and password, instead it was an issue with the menu not updating properly after adding the first server.
Thanks for the report!
