### ISSUE TITLE
Too many levels of menu

### ISSUE THREAD

**Issue by gerv** [dirkjanm/firefox-send-to-xbmc#59]
The current menu structure for right-click is:

Send to Kodi -> Play On -> Slice

That's one or two menus too deep. If you only have one server, there should be a single menu item "Send to Kodi (Slice)". If I want to add more servers, I can go to the addon prefs.

If I have two servers, it should be: Send to Kodi -> Play on Slice | Play on FooBox | Manage Servers

There's no need for the extra level of indirection.

**Comment by dirkjanm** [comment]
Can you let me know which version you are using? I'm working on v3.0 now so that one might still have some bugs.

**Comment by gerv** [comment]
I'm using Send to Kodi 3.0.0b1 on Firefox 58.0a1 on Ubuntu Linux 16.04 LTS.

**Comment by dirkjanm** [comment]
Duplicate of #5 - closing.
