### ISSUE TITLE
No buttons in Firefox

### ISSUE THREAD

**Issue by Muurahainen** [dirkjanm/firefox-send-to-xbmc#7]
After installation buttons on Firefox bar or in right click menu don't appear.
Quite unusable without them. Version 2.1.0

**Comment by dirkjanm** [comment]
What kind of link are you right-clicking on? Is it a direct link to YouTube and/or a video/mp3 file?

**Comment by Muurahainen** [comment]
Well now this is bit awkward.
YouTube link that i have tried before now has function under right click button.

But still in YouTube after I open "suggested" video from right side XBMC link get's lost and also right click won't work anymore.

**Comment by dirkjanm** [comment]
Strange, could you send me the full url of the video you are having the problem with (or one of the videos you have this with)?

**Comment by Muurahainen** [comment]
Here you go: https://www.youtube.com/watch?v=BEG-ly9tQGk

After i open that link in my browser videos on right don't have Send to XBMC functionality.

**Comment by Muurahainen** [comment]
BTW that link that I gave works on this page when right clicked.

**Comment by dirkjanm** [comment]
I'm having the same problem here, will investigate.

**Comment by Muurahainen** [comment]
Thanks for great support.

**Comment by dirkjanm** [comment]
Fixed in 57cd48ca9f62a20a6157c32141e270bad9cf4834
