### ISSUE TITLE
"add" button in firefox, addon preferences does nothing

### ISSUE THREAD

**Issue by deagon88** [dirkjanm/firefox-send-to-xbmc#8]
browser: Firefox: 35.0
os/system: Arch Linux
addon: Send to XBMC 2.1.0

issue: The server "add" button located in  "tools -> addons -> extensions -> preferences for 'Send to XBMC' doesn't do anything. No server/xbmc/kodi entry is added. Possibly unrelated but the server is listening on a non standard port '8050' and its password does contain special characters *#.

**Comment by dirkjanm** [comment]
I'm not sure what the issue is but somebody else reported it too. If you have some time, would you help me out with this and install the xpi directly from the debug branch in the repository (download the file and just drag/drop it to firefox to install):
https://github.com/dirkjanm/firefox-send-to-xbmc/blob/debug/send-to-xbmc.xpi?raw=true
This should have a debug section on the settings page, let me know what shows up there when you load the page. Thanks!

**Comment by deagon88** [comment]
I gave it a shot but there was no debugging output. It's almost like I couldnt click the 'add' button. Firefox was updated to 35.0.1 and the issue persisted.

![screenshot_2015-01-28_22-01-32](https://cloud.githubusercontent.com/assets/10428982/5948075/f7df39dc-a739-11e4-8646-dbe8e80f23ca.png)

I'm going to try this addon with a clean firefox profile (sorry, I probably should of tried that before I opened the bug :P ) and see how it goes.

**Comment by dirkjanm** [comment]
Well no debug output helps as well since it tells me the script that is supposed to get initialized doesn't even run at all. What is the exact url of the config page that you are on?

**Comment by deagon88** [comment]
The url with my original firefox profile is "resource://jid0-ycm0p5wlcgjvbjczhausq5h26wm-at-jetpack/send-to-xbmc/data/preferences.html"

With a clean profile your addon works flawlessly. So it appears this isn't really a bug with your addon but with my setup. See below.

![screenshot_2015-01-28_22-11-46](https://cloud.githubusercontent.com/assets/10428982/5948205/03706fcc-a73b-11e4-9f19-d7b75ecd7e3d.png)

**Comment by deagon88** [comment]
I found out whats leading to the issue. It's firefox's privacy settings. When its set to 'never remember history' or 'use custom settings for history' your addon doesn't work. However when it's set to "remember history" your addon works normally. I checked this with a clean firefox profile too, same thing.

**Comment by dirkjanm** [comment]
The addon doesn't work with private browsing (since it needs to ask special permissions for that), I guess when Firefox is set to not remember anything it is in private browsing all the time, so that would probably be why the addon doesn't load.

**Comment by deagon88** [comment]
ok, I got it. Thanks for your help. Issue is closed as this doesnt appear to be a bug.

**Comment by dirkjanm** [comment]
I've added support for private windows in 24a518843b0a746216518151de34bdf0ffaba508 so it should work also when FF is set to not remember history
